spring:
  application:
    name: authentication-service
  config:
    import: "optional:configserver:http://localhost:8888"
  main:
    allow-circular-references: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
